surface.CreateFont("ofgui_eva", {size = 48, weight = 300, antialias = true, extended = true, font = "Roboto Condensed"})
surface.CreateFont("ofgui_gigantic", {size = 42, weight = 300, antialias = true, extended = true, font = "Roboto Condensed"})
surface.CreateFont("ofgui_huge", {size = 32, weight = 300, antialias = true, extended = true, font = "Roboto Condensed"})
surface.CreateFont("ofgui_big", {size = 26, weight = 300, antialias = true, extended = true, font = "Roboto Condensed"})
surface.CreateFont("ofgui_medium", {size = 23, weight = 350, antialias = true, extended = true, font = "Roboto Condensed"})
surface.CreateFont("ofgui_small", {size = 22, weight = 300, antialias = true, extended = true, font = "Roboto Condensed"})
surface.CreateFont("ofgui_tiny", {size = 16, weight = 300, antialias = true, extended = true, font = "Roboto Condensed"})
surface.CreateFont("ofgui_extratiny", {size = 14, weight = 300, antialias = true, extended = true, font = "Roboto Condensed"})