surface.CreateFont("ofgui_eva", {size = 48 * OFGUI.ScreenScale, weight = 300, antialias = true, extended = true, font = "HONOR Sans CN"})
surface.CreateFont("ofgui_gigantic", {size = 42 * OFGUI.ScreenScale, weight = 300, antialias = true, extended = true, font = "HONOR Sans CN"})
surface.CreateFont("ofgui_huge", {size = 32 * OFGUI.ScreenScale, weight = 300, antialias = true, extended = true, font = "HONOR Sans CN"})
surface.CreateFont("ofgui_big", {size = 26 * OFGUI.ScreenScale, weight = 300, antialias = true, extended = true, font = "HONOR Sans CN"})
surface.CreateFont("ofgui_medium", {size = 23 * OFGUI.ScreenScale, weight = 350, antialias = true, extended = true, font = "HONOR Sans CN"})
surface.CreateFont("ofgui_small", {size = 22 * OFGUI.ScreenScale, weight = 300, antialias = true, extended = true, font = "HONOR Sans CN"})
surface.CreateFont("ofgui_tiny", {size = 16 * OFGUI.ScreenScale, weight = 300, antialias = true, extended = true, font = "HONOR Sans CN"})
surface.CreateFont("ofgui_extratiny", {size = 14 * OFGUI.ScreenScale, weight = 300, antialias = true, extended = true, font = "HONOR Sans CN"})